version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  environment:
      - DB_HOST=stacktalleraws-rdsinstance-hjq7zkuf8r5c.cvzx8qh37fom.us-east-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=adminpass
      - DB_NAME=crud_db
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
