version: '3'
services:
  app:
    build: ./app
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
