version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

    environment:
        - DB_HOST=teststack-rdsinstance-tc2ipnofo2uq.cvzx8qh37fom.us-east-1.rds.amazonaws.com
        - DB_USER=admin
        - DB_PASSWORD=adminpass
        - DB_NAME=crud_db
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
